<?php


namespace backend\controllers;


use backend\helpers\FirestoreHelper;
use backend\models\User;
use common\models\FreeQar;
use common\models\FreeSites;
use common\models\FreeUsers;
use common\models\Settings;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

class FreeController extends Controller
{


    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [
                            User::ROLE_ADMIN,
                            User::ROLE_ADMIN_VIEW
                        ],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'pull-fire-store' => ['POST'],
                ],
            ],
        ];
    }

    public $fireStoreHelper;

    /**
     * Initialize controller with dependencies
     */
    public function init()
    {
        $this->fireStoreHelper = new FirestoreHelper();
        parent::init(); // TODO: Change the autogenerated stub
    }


    /**
     * Default action
     */
    public function actionIndex(){
        $freeUsers = FreeUsers::find()->count();
        $freeQar = FreeQar::find()->count();
        $freeSites = FreeSites::find()->count();

        return $this->render("index", [
            'lastSync' => Settings::findOne(FirestoreHelper::SYNC_TIME_SETTING),
            'freeUsers' => $freeUsers,
            'freeQar' => $freeQar,
            'freeSites' => $freeSites,
        ]);
    }


    public function actionPullFireStore(){
        $dbUpdated = $this->fireStoreHelper->updateFreeVersionDb();
        if($dbUpdated){
            \Yii::$app->session->setFlash("success", "Successfully updated free version data");
        }else{
            \Yii::$app->session->setFlash("danger", "Successfully updated free version data");
        }
        return $this->redirect(["free/index"]);
    }
}