version: '3'
services:
  frontend:
    build: frontend
    container_name: cnqa.frontend
    ports:
      - "24080:80"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    depends_on:
      - cnqa_db
    networks:
      - cnqa-docker-network
  backend:
    build: backend
    container_name: cnqa.backend
    ports:
      - "24081:80"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    depends_on:
      - cnqa_db
    networks:
      - cnqa-docker-network
  cnqa_db:
    container_name: cnqa.db
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=cnqa_secret
      - MYSQL_DATABASE=cnqa
      - MYSQL_USER=cnqa
      - MYSQL_PASSWORD=cnqa_secret
    ports:
      - "24082:3306"
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - cnqa-docker-network
networks:
  cnqa-docker-network:
    driver: bridge

