<?php


namespace console\controllers;
use backend\helpers\FirestoreHelper;
use yii\console\Controller;

class FireStoreController extends Controller
{
    public $fireStoreHelper;

    /**
     * Initialize controller with dependencies
     */
    public function init()
    {
        $this->fireStoreHelper = new FirestoreHelper();
        parent::init(); // TODO: Change the autogenerated stub
    }


    /**
     * Default action
     */
    public function actionIndex(){
        $dbUpdated = $this->fireStoreHelper->updateFreeVersionDb();
        if($dbUpdated)
            print "Free Version Data Updated successfully \n";
        else
            print "Could not update database \n";
    }
}